# Generated by Django 5.1 on 2025-10-16 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("quantity", models.IntegerField()),
                ("location", models.CharField(max_length=255)),
            ],
            options={
                "permissions": [
                    ("view_inventory", "Can view inventory"),
                    ("add_inventory", "Can add inventory"),
                    ("update_inventory", "Can update inventory"),
                ],
            },
        ),
    ]
