# Generated by Django 5.1 on 2025-10-16 13:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_team_alter_product_options_product_created_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Site",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("code", models.CharField(max_length=50, unique=True)),
                ("address", models.TextField(blank=True)),
                ("contact_person", models.CharField(blank=True, max_length=255)),
                ("contact_phone", models.CharField(blank=True, max_length=20)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="UnitOfMeasure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("abbreviation", models.CharField(max_length=20)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Unit of Measure",
                "verbose_name_plural": "Units of Measure",
                "ordering": ["name"],
            },
        ),
        migrations.AlterModelOptions(
            name="itemrequest",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Item Request",
                "verbose_name_plural": "Item Requests",
            },
        ),
        migrations.AlterModelOptions(
            name="itemrequestline",
            options={
                "verbose_name": "Item Request Line",
                "verbose_name_plural": "Item Request Lines",
            },
        ),
        migrations.RemoveField(
            model_name="itemrequest",
            name="notes",
        ),
        migrations.AddField(
            model_name="itemrequest",
            name="rejection_reason",
            field=models.TextField(
                blank=True, help_text="Reason for rejection if applicable"
            ),
        ),
        migrations.AddField(
            model_name="itemrequestline",
            name="remarks",
            field=models.TextField(
                blank=True, help_text="Specific remarks for this item"
            ),
        ),
        migrations.AlterField(
            model_name="itemrequest",
            name="purpose",
            field=models.TextField(help_text="Purpose/Remarks for this request"),
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "code",
                    models.CharField(
                        help_text="Department code (e.g., IT, HR, OPS)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "manager",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="managed_departments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["code"],
            },
        ),
        migrations.AddField(
            model_name="team",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="teams",
                to="inventory.department",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="employees",
                to="inventory.department",
            ),
        ),
        migrations.AlterField(
            model_name="itemrequest",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="item_requests",
                to="inventory.department",
            ),
        ),
        migrations.AddField(
            model_name="itemrequestline",
            name="destination_site",
            field=models.ForeignKey(
                blank=True,
                help_text="Site where item will be delivered",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="requested_items",
                to="inventory.site",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="unit_of_measure",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="products",
                to="inventory.unitofmeasure",
            ),
        ),
    ]
