# Generated by Django 5.1 on 2025-10-17 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0005_currency_alter_purchaseorder_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseorder",
            name="external_po_number",
            field=models.CharField(
                blank=True,
                help_text="External/Reference PO number from another system",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="po_number",
            field=models.CharField(
                help_text="Internal PO number (auto-generated)",
                max_length=100,
                unique=True,
            ),
        ),
    ]
